<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>asm</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>6502 Assembly (DASM)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i)\b(adc|and|asl|bit|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|sbc|sec|sed|sei|sta|stx|sty|tax|txa|tay|tya|tsx|txs)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(bcc|bcs|beq|bmi|bne|bpl|brk|bvc|bvs|jmp|jsr|rti|rts)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\.\b(byte|hex|set|word)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(align)\b</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(endm|mac|repeat|repend|subroutine)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(incbin|include|org|processor)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.label.local</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(VSYNC|VBLANK|WSYNC|RSYNC|NUSIZ0|NUSIZ1|COLUP0|COLUP1|COLUPF|COLUBK|CTRLPF|REFP0|REFP1|PF0|PF1|PF2|RESP0|POSH2|RESP1|RESM0|RESM1|RESBL|AUDC0|AUDC1|AUDF0|AUDF1|AUDV0|AUDV1|GRP0|GRP1|ENAM0|ENAM1|ENABL|HMP0|HMP1|HMM0|HMM1|HMBL|VDELP0|VDELP1|VDELBL|RESMP0|RESMP1|HMOVE|HMCLR|CXCLR|CXM0P|CXM1P|CXP0FB|CXP1FB|CXM0FB|CXM1FB|CXBLPF|CXPPMM|INPT0|INPT1|INPT2|INPT3|INPT4|INPT5|SWCHA|SWACNT|SWCHB|SWBCNT|INTIM|TIMINT|TIM1T|TIM8T|TIM64T|T1024T|TIM1I|TIM8I|TIM64I|T1024I)\b</string>
			<key>name</key>
			<string>constant.vcs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#?\$[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>{[0-9]+}</string>
			<key>name</key>
			<string>variable.parameter.macro</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.assembly.6502.dasm</string>
	<key>uuid</key>
	<string>8D1E7063-570E-4E88-AF2E-EA3CE330B2D3</string>
</dict>
</plist>
